tasks:
  - init: |
      npm install
      npm run build
      npm install http-server && node_modules/http-server/bin/http-server
    command: |
      gp preview http://localhost:8080

github:
  prebuilds:
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false
    addLabel: false
